### ISSUE TITLE
[BUG]: Write text does not write certain special characters

### ISSUE THREAD

**Issue by 4s3ti** [streamdeck-linux-gui/streamdeck-linux-gui#164]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

When using the write text funcionality on wayland, special characters such as `äëýþäçéè` are not written. 

### Steps to reproduce the behavior

1. Use Streamdeck-linux-gui on wayland session
2. Set a button to write text with any of those characters
3. verify that they are not written out

### Expected behavior

Special characters should be written like the other ones. 

### System Information

```
                   -`                    f0rs3ti@deathstar
                  .o+`                   -----------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: MS-7C84 1.0
               `+oooooo:                 Kernel: 6.7.1-zen1-1-zen
               -+oooooo+:                Uptime: 8 mins
             `/:-:++oooo+:               Packages: 1257 (pacman), 6 (flatpak)
            `/++++/+++++++:              Shell: bash 5.2.26
           `/++++++++++++++:             Resolution: 5120x1440
          `/+++ooooooooooooo/`           WM: sway
         ./ooosssso++osssssso+`          Terminal: tmux
        .oossssso-````/ossssss+`         CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz
       -osssssso.      :ssssssso.        GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT
      :osssssss/        osssso+++.       Memory: 5726MiB / 32015MiB
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

### Stream Deck Version

```
$git describe --long --tags --exclude='*[a-zA-Z][a-zA-Z]*' | sed -E 's/^v//;s/([^-]*-g)/r\1/;s/-/./g'
4.1.0.r5.g735b238
```

**Comment by ajbucci** [comment]
I think that we should consider reintroducing the pynput dependency. If we detect a user is on an X session then we should use pynput, otherwise we can use uinput.

The major downside of uinput/wayland is that uinput works only with _keycodes_, not _keysyms_:
1) It does not support inputting any accented or unicode characters ... we are restricted to what keycodes are available in the kernel: [linux/input-event-codes.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h )
The current workaround (press CTRL+SHIFT, press/release U + unicode hex codepoint chars, release CTRL+SHIFT) will not work in every application/environment
#160 
2) It does not respect layouts, since it sends raw keycodes... in order to support layouts we would have to translate ```keysym_layout -> keycode```, but determining the keyboard layout on linux is non-trivial 
#157

Honestly the near-term looks pretty bleak for wayland support that _just works_. I've seen other projects mention [libei](https://gitlab.freedesktop.org/libinput/libei) as a potential solution, but looking at the libei documentation it only looks like it would solve layout translation (2): [ei_keyboardkey](https://libinput.pages.freedesktop.org/libei/interfaces/ei_keyboard/index.html#ei_keyboardkey). As far as I can tell, there doesn't appear to be any way to inject arbitrary unicode characters.

One potential workaround I was investigating was using QClipboard. The general approach was:

- Create QClipboard object
- Save current clipboard contents
- Set system clipboard to contents of (write text)
- Use UInput KEY_PASTE to trigger a paste operation
- Set system clipborad back to previous clipboard contents

This approach worked well for most apps. However, none of the GTK apps I tested would paste when the KEY_PASTE keycode was sent with UInput. They would only paste the contents of the clipboard using the app specific paste keycode combination (usually CTRL+V). Perhaps there are reliable ways to trigger paste that work everywhere, but I'm not currently aware of any.
