### ISSUE TITLE
[BUG]:  Wrong text shadow for multiline text

### ISSUE THREAD

**Issue by rkmax** [streamdeck-linux-gui/streamdeck-linux-gui#58]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

The text shadow is wrong then the text is a multiline, This happens when the lines length is not equal

### Steps to reproduce the behavior

1. Set as "Label" the following text
```
ABC

ABCD
```
2. Change the background to yellow or something different than black
3. Observe the results

### Expected behavior

The text-shadow should behave equally on both texts lines equally

### Screenshots

- ![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/8d2ed95d-0596-46c5-99f0-87a43afd3f2b)
- ![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/43a65b44-6c04-493f-a889-6de1bef1dd44)

### System Information

* Python 3.11
* StreamDeckUI 3.1.0

### Stream Deck Version

Standard MK.2

**Comment by ajbucci** [comment]
I have a fix for this and another bug I discovered while investigating. However, it appears that the proper implementation of this feature hinders readability, and since the text-glow/blurred-black-outline isn't user-adjustable I believe we should disable it completely until we make it customizable. Does anyone object to this approach? @rkmax @4s3ti

**Comment by rkmax** [comment]
I'd like to be fixed that disable. The glow improves the readability.

Also which other bug did you discover ?

**Comment by rkmax** [comment]
I have a working multiline text with the black outline [here](https://github.com/rkmax/streamdeck-ui/blob/plugins/streamdeck_ui/display/text_filter.py) in my branch (this branch is very far from current develop branch)  you can use it as example
![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/3e6fa6be-bb9f-438b-bee1-7d9ce6fcbc40)

I think is easy to adapt to the current text_filter.py which include some extra properties

**Comment by ajbucci** [comment]
Here are two options:

(1) a simple fix to the current method, using backdrop_draw.multiline_text instead of backdrop_draw.text to render the black blurred background text:
![multiline-background-blur-fix](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/28697382/d7240a72-b00a-4507-9fea-503517685276)

(2) a change in approach, using stroke_width (=2) and stroke_fill (="black") in foreground_draw.multiline_text, which results in this:
![multiline-strokewidth2-spacing0](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/28697382/a66eab08-0841-4413-babb-146e11fc006d)

Using (1) results in some clipping of the blurred black background text when left, right, top, or bottom aligned:
![multiline-background-blur-fix-left](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/28697382/bc82e420-734d-4008-b650-5dd642111380)

Using (2) we do not see this because foreground_draw.multiline_text accounts for the stroke_width when positioning the image:
![multiline-strokewidth2-left](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/28697382/54bc20ac-d608-4f1f-97f8-e20fd137e9a0)

To prevent the clipping while still using approach (1) would require a different method of placing the label. Using (2) also has the bonus of making the stroke_width easily user customizable.

**Comment by ajbucci** [comment]
> I have a working multiline text with the black outline [here](https://github.com/rkmax/streamdeck-ui/blob/plugins/streamdeck_ui/display/text_filter.py) in my branch (this branch is very far from current develop branch) you can use it as example ![image](https://user-images.githubusercontent.com/395707/265275974-3e6fa6be-bb9f-438b-bee1-7d9ce6fcbc40.png)
> 
> I think is easy to adapt to the current text_filter.py which include some extra properties. I think that logic has a problem with the alignement to bottom

@rkmax Using your method do you have any clipping issues at the button edges?

**Comment by rkmax** [comment]
I think also it's worth to review new functionalities in PIL any solution works as soon keep the capabilities of text filter

- foreground color
- background color
- font size
- font name
- black outline (we can also add user options to customized, width, color, or remove it) 
- multi line support

**Comment by rkmax** [comment]
> > I have a working multiline text with the black outline [here](https://github.com/rkmax/streamdeck-ui/blob/plugins/streamdeck_ui/display/text_filter.py) in my branch (this branch is very far from current develop branch) you can use it as example ![image](https://user-images.githubusercontent.com/395707/265275974-3e6fa6be-bb9f-438b-bee1-7d9ce6fcbc40.png)
> > I think is easy to adapt to the current text_filter.py which include some extra properties. I think that logic has a problem with the alignement to bottom
> 
> @rkmax Using your method do you have any clipping issues at the button edges?

this method has issues when text is aligned to bottom

**Comment by rkmax** [comment]
this can marked as close

**Comment by 4s3ti** [comment]
issues should be closed only after released on main branch. being in development doesn't necessarily means its done.

**Comment by rkmax** [comment]
Thank you for the clarification

**Comment by 4s3ti** [comment]
done at: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v3.2.0
